/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DIDRegistry__factory } from "./DIDRegistry__factory";
export { RevocationRegistry__factory } from "./RevocationRegistry__factory";
