/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  RevocationRegistry,
  RevocationRegistryInterface,
} from "../RevocationRegistry";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "credentialHash",
        type: "bytes32",
      },
    ],
    name: "checkRevocation",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "isRevoked",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "credentialHash",
        type: "bytes32",
      },
    ],
    name: "revoke",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50600080546001600160a01b031916331790556101fa806100316000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80634294857f14610051578063b75c7dc614610089578063ba1b511b1461009e578063f851a440146100c1575b600080fd5b61007461005f3660046101ab565b60016020526000908152604090205460ff1681565b60405190151581526020015b60405180910390f35b61009c6100973660046101ab565b6100ec565b005b6100746100ac3660046101ab565b60009081526001602052604090205460ff1690565b6000546100d4906001600160a01b031681565b6040516001600160a01b039091168152602001610080565b6000546001600160a01b031633146101385760405162461bcd60e51b815260206004820152600a60248201526927b7363c9030b236b4b760b11b60448201526064015b60405180910390fd5b60008181526001602052604090205460ff161561018d5760405162461bcd60e51b81526020600482015260136024820152725a6174656e20697074616c206564696c6d697360681b604482015260640161012f565b6000908152600160208190526040909120805460ff19169091179055565b6000602082840312156101bd57600080fd5b503591905056fea26469706673582212200141df87a8bac4103c8e47a2d1880c8a62d362198945a875f1cc898a365fbc2064736f6c634300081c0033";

type RevocationRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RevocationRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RevocationRegistry__factory extends ContractFactory {
  constructor(...args: RevocationRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RevocationRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RevocationRegistry__factory {
    return super.connect(runner) as RevocationRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RevocationRegistryInterface {
    return new Interface(_abi) as RevocationRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RevocationRegistry {
    return new Contract(address, _abi, runner) as unknown as RevocationRegistry;
  }
}
